#!/bin/sh
set -e

case "$1" in
    configure)
        # Byte-compile Python files for the current default interpreter
        py3compile -p autolatex-astah-sysml /usr/lib/python3/dist-packages/autolatex2/translators/astah-sysml
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
